import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

/**
 * jsdom runs with `css: false` (vitest.config), so stylesheets are NOT applied
 * and computed visibility/opacity/contrast are not testable. CSS-driven ACs are
 * guarded statically here: read styles.css (co-located via import.meta.url —
 * ESM-safe, no `__dirname`), collapse whitespace, and regex-assert the rules.
 * (postcss is not a direct dependency, so a normalized-regex guard is the
 * pragmatic choice; contrast can't be computed from CSS strings so AC2/AC5
 * assert the token usage that QUE-37 established.)
 */
const here = dirname(fileURLToPath(import.meta.url));
const css = readFileSync(resolve(here, 'styles.css'), 'utf8').replace(/\s+/g, ' ');
// The vendored token copy (generated by scripts/sync-design-tokens.mjs from the
// canonical shared/design-tokens/tokens.css). Read statically to guard the
// QUE-47 light/dark token structure + the semantic on-surface rename.
const tokens = readFileSync(resolve(here, 'styles/_tokens.css'), 'utf8').replace(/\s+/g, ' ');

/** Extracts the declaration block of a selector (greedy to the closing brace). */
function rule(sel: string): string {
  const escaped = sel.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const re = new RegExp(`${escaped}\\s*\\{([^}]*)\\}`);
  const m = css.match(re);
  if (!m) throw new Error(`selector not found: ${sel}`);
  return m[1];
}

describe('styles.css AC guards', () => {
  it('AC2: now-serving counter uses --accent-on-surface (QUE-37/QUE-47 regression)', () => {
    expect(rule('.now-serving__counter')).toContain('color: var(--accent-on-surface)');
  });

  it('AC5: connection closed uses --danger-on-surface (QUE-37/QUE-47 regression)', () => {
    expect(rule('.connection-status--closed')).toContain('color: var(--danger-on-surface)');
  });

  it('AC3: now-serving number is a width+height container-query clamp (cqw + cqh) + nowrap + a 4K media tier', () => {
    // The card is a size container so the number scales to BOTH its widget
    // wrapper width (cqw, the one-line guarantee) and its height (cqh, fits
    // short cells such as a 1-row grid span), not the viewport.
    expect(rule('.now-serving')).toContain('container-type: size');
    const number = rule('.now-serving__number');
    // cqw stays the width one-line driver; the cqh cap (inside min()) also
    // shrinks the number for short (h=1) cells so it never overflows/clips.
    expect(number).toContain('min(18cqw, 24cqh)');
    expect(number).toContain('cqh');
    expect(number).toContain('18cqw');
    expect(number).toContain('white-space: nowrap');
    expect(css).toMatch(/@media\s*\(min-width:\s*2560px\)/);
    // The 4K tier also sizes to the (now wider) column and stays one line.
    const tierMatch = css.match(
      /@media\s*\(min-width:\s*2560px\)\s*\{([^}]*(?:\{[^}]*\}[^}]*)*)\}/,
    );
    expect(tierMatch?.[1]).toContain('clamp(5rem, min(18cqw, 24cqh), 40rem)');
  });

  it('AC3: panel containment — now-serving + call-history allow shrinking (min-width: 0)', () => {
    expect(rule('.now-serving')).toContain('min-width: 0');
    expect(rule('.call-history')).toContain('min-width: 0');
  });

  it('AC4: call-history items use a hairline divider, not nested card backgrounds', () => {
    const item = rule('.call-history__item');
    expect(item).toContain('border-bottom: 1px solid var(--text-muted)');
    expect(item).not.toContain('background:');
    expect(item).not.toContain('border-radius:');
    // list gap cleared — padding+border carry spacing, gap+border would double up.
    expect(rule('.call-history__list')).toContain('gap: 0');
    // last child drops the divider (no orphan rule under the final item).
    expect(css).toContain('.call-history__item:last-child');
  });

  it('counters-serving mirrors call-history: surface card + hairline dividers + containment', () => {
    // Surface card via per-service tokens (no new shared token minted).
    const panel = rule('.counters-serving');
    expect(panel).toContain('background: var(--surface)');
    expect(panel).toContain('border-radius: var(--radius)');
    expect(panel).toContain('min-width: 0'); // grid-cell containment (AC3)
    expect(panel).toContain('overflow: hidden');
    // Hairline divider between rows, no nested card background.
    const item = rule('.counters-serving__item');
    expect(item).toContain('border-bottom: 1px solid var(--text-muted)');
    expect(item).not.toContain('background:');
    expect(item).not.toContain('border-radius:');
    expect(rule('.counters-serving__list')).toContain('gap: 0');
    expect(css).toContain('.counters-serving__item:last-child');
    // Idle counter (no active ticket): the em-dash number is muted via the
    // existing --text-muted token — no new shared token minted.
    expect(css).toContain('.counters-serving__item--idle');
    expect(css).toContain(
      '.counters-serving__item--idle .counters-serving__number',
    );
    expect(css).toMatch(
      /\.counters-serving__item--idle\s+\.counters-serving__number\s*\{[^}]*color:\s*var\(--text-muted\)/,
    );
  });

  it('waiting-queue mirrors call-history: surface card + hairline dividers + containment', () => {
    // Surface card via per-service tokens (no new shared token minted).
    const panel = rule('.waiting-queue');
    expect(panel).toContain('background: var(--surface)');
    expect(panel).toContain('border-radius: var(--radius)');
    expect(panel).toContain('min-width: 0'); // grid-cell containment (AC3)
    expect(panel).toContain('overflow: hidden');
    // Hairline divider between rows, no nested card background.
    const item = rule('.waiting-queue__item');
    expect(item).toContain('border-bottom: 1px solid var(--text-muted)');
    expect(item).not.toContain('background:');
    expect(item).not.toContain('border-radius:');
    expect(rule('.waiting-queue__list')).toContain('gap: 0');
    expect(css).toContain('.waiting-queue__item:last-child');
    // Position column uses --text-muted and a fixed min-width so numbers align.
    expect(rule('.waiting-queue__position')).toContain('color: var(--text-muted)');
    // 4K media tier scales the waiting-queue typography up (mirror of call-history).
    expect(css).toMatch(/@media\s*\(min-width:\s*2560px\)[\s\S]*\.waiting-queue__number\s*\{[^}]*clamp/);
  });

  it('waiting-queue scales rows to the panel height (cqh) + scrollable list (no clip)', () => {
    // The panel is a size container so children can scale to its height via cqh
    // units — all VISIBLE_LIMIT items always fit the panel regardless of its
    // height (responsive). The panel height is determinate because the
    // .tv-board__widget wrapper resolves its grid row span (proportional to
    // the manager-configured h) and is itself a flex column.
    const panel = rule('.waiting-queue');
    expect(panel).toContain('container-type: size');
    expect(panel).toContain('display: flex');
    expect(panel).toContain('flex-direction: column');
    // The list is scrollable (safety-net) — never clipped/invisible.
    const list = rule('.waiting-queue__list');
    expect(list).toContain('overflow-y: auto');
    expect(list).toContain('flex: 1 1 auto');
    expect(list).toContain('min-height: 0');
    // Item font/padding scale to the panel height via cqh clamps.
    expect(rule('.waiting-queue__number')).toContain('clamp(');
    expect(rule('.waiting-queue__number')).toMatch(/cqh/);
    expect(rule('.waiting-queue__item')).toMatch(/cqh/);
  });

  it('call-history scales rows to the panel height (cqh) + scrollable list (no clip)', () => {
    // Mirrors .waiting-queue: a size container so rows scale to the panel
    // height via cqh units — fits a short (h=1) cell without clipping.
    const panel = rule('.call-history');
    expect(panel).toContain('container-type: size');
    expect(panel).toContain('display: flex');
    expect(panel).toContain('flex-direction: column');
    // The list is scrollable (safety-net) — never clipped/invisible.
    const list = rule('.call-history__list');
    expect(list).toContain('overflow-y: auto');
    expect(list).toContain('flex: 1 1 auto');
    expect(list).toContain('min-height: 0');
    // Item font/padding scale to the panel height via cqh clamps.
    expect(rule('.call-history__number')).toContain('clamp(');
    expect(rule('.call-history__number')).toMatch(/cqh/);
    expect(rule('.call-history__item')).toMatch(/cqh/);
  });

  it('counters-serving scales rows to the panel height (cqh) + scrollable list (no clip)', () => {
    // Mirrors .waiting-queue/.call-history: a size container so rows scale to
    // the panel height via cqh units — fits a short (h=1) cell without clipping.
    const panel = rule('.counters-serving');
    expect(panel).toContain('container-type: size');
    expect(panel).toContain('display: flex');
    expect(panel).toContain('flex-direction: column');
    // The list is scrollable (safety-net) — never clipped/invisible.
    const list = rule('.counters-serving__list');
    expect(list).toContain('overflow-y: auto');
    expect(list).toContain('flex: 1 1 auto');
    expect(list).toContain('min-height: 0');
    // Item font/padding scale to the panel height via cqh clamps.
    expect(rule('.counters-serving__number')).toContain('clamp(');
    expect(rule('.counters-serving__number')).toMatch(/cqh/);
    expect(rule('.counters-serving__item')).toMatch(/cqh/);
  });

  it('tv-board__grid is a 12-column CSS grid (replaces the old 1D flex-column of panels)', () => {
    const grid = rule('.tv-board__grid');
    expect(grid).toContain('display: grid');
    expect(grid).toContain('grid-template-columns: repeat(12, 1fr)');
    expect(grid).toContain('grid-auto-rows: 1fr');
    expect(grid).toContain('flex: 1');
    expect(grid).toContain('min-height: 0');
    expect(grid).toContain('min-width: 0');
    // The old flex-column panels + panel wrapper rules are gone. Anchor on
    // the selector followed by `{` so `.tv-board__panels-empty` (kept) is not
    // a false positive for `.tv-board__panels`.
    expect(css).not.toMatch(/\.tv-board__panels\s*\{/);
    expect(css).not.toMatch(/\.tv-board__panel\s*\{/);
    expect(css).not.toContain('.tv-board__active-grid');
    expect(css).not.toContain('.tv-board__active-side');
  });

  it('tv-board__widget wrapper is a flex column with containment (min-height: 0, min-width: 0) + fills its child', () => {
    const widget = rule('.tv-board__widget');
    expect(widget).toContain('display: flex');
    expect(widget).toContain('flex-direction: column');
    expect(widget).toContain('min-height: 0');
    expect(widget).toContain('min-width: 0');
    // The direct-child fill rule stretches the component card to the grid area.
    const fill = rule('.tv-board__widget > *');
    expect(fill).toContain('flex: 1 1 auto');
    expect(fill).toContain('min-height: 0');
  });

  it('tv-board__storename caps at 2 lines + shrinks in the header row (manager feedback: "mempet kanan kiri")', () => {
    // A long store name used to fill the header row edge-to-edge and wrap
    // without limit, pushing the connection badge and the grid down. It is a
    // flex item sharing the row with the badge, so it needs min-width: 0 to
    // shrink below its intrinsic content width and a 2-line clamp to cap its
    // height (overflow ellipsised). The header gap gives the right-side
    // breathing room the name was missing against the badge.
    const header = rule('.tv-board__header');
    expect(header).toContain('gap: 1rem');
    const name = rule('.tv-board__storename');
    expect(name).toContain('min-width: 0');
    expect(name).toContain('flex: 1 1 auto');
    expect(name).toContain('-webkit-line-clamp: 2');
    expect(name).toContain('line-clamp: 2');
    expect(name).toContain('-webkit-box-orient: vertical');
    expect(name).toContain('overflow: hidden');
    // The badge is the other flex item in the header row — it must keep its
    // size while the name absorbs the slack (flex-shrink: 0 encodes the
    // "badge keeps its size" half of the contract the comment states).
    expect(rule('.connection-status')).toContain('flex-shrink: 0');
  });

  it('AC6: the active board is the single always-visible layer (no standby/crossfade)', () => {
    // The standby/promosi panel was removed (it flickered on the crossfade);
    // the active board is now a plain flex column filling the main area — no
    // overlay, no --hidden modifier, no crossfade. The promo standby overlay
    // (full-screen media crossfade, conditionally shown) stays REMOVED — these
    // negations guard that. The intentional running-text disclaimer marquee
    // (fixed, always-visible, no media, reduced-motion guarded) is a distinct
    // element and is asserted positively in the dedicated test below.
    expect(css).not.toContain('.standby');
    expect(css).not.toContain('--hidden');
    expect(css).not.toContain('position: absolute');
    expect(css).not.toContain('transition: opacity');
    const active = rule('.tv-board__active');
    expect(active).toContain('display: flex');
    expect(active).toContain('flex-direction: column');
    expect(active).toContain('height: 100%');
    expect(active).toContain('min-height: 0');
  });

  it('RunningText disclaimer marquee: grid widget, reduced-motion guarded', () => {
    // The disclaimer marquee (manager feedback) is intentional and distinct
    // from the removed promo standby overlay. Positive guards for its presence
    // + the a11y/interaction baseline (reduced-motion pause). The TV does NOT
    // import _interactions.css, so the reduced-motion guard is inlined in
    // styles.css (anchor `reduce\)\s*\{` — the `)` sits between the keyword
    // and the block brace, so `reduce\s*\{` would silently never match). The
    // marquee is now a grid widget (no fixed `.tv-board__footer` rule) — it
    // fills its grid cell via the `.tv-board__widget > *` flex-fill rule.
    expect(css).toContain('@keyframes marquee');
    expect(css).toMatch(
      /prefers-reduced-motion:\s*reduce\)\s*\{[^}]*\.running-text__track/,
    );
    const viewport = rule('.running-text');
    expect(viewport).toContain('overflow: hidden');
    expect(viewport).toContain('white-space: nowrap');
    expect(viewport).toContain('display: flex');
    expect(viewport).toContain('align-items: center');
    const track = rule('.running-text__track');
    expect(track).toContain('animation: marquee');
    // The old fixed-footer rule is gone (runningText is a grid widget now).
    expect(css).not.toContain('.tv-board__footer');
  });

  it('AC8: now-serving eyebrow letter-spacing ≤ 0.08em', () => {
    const r = rule('.now-serving__label');
    const ls = r.match(/letter-spacing:\s*([\d.]+)em/);
    expect(ls, 'letter-spacing must be set').not.toBeNull();
    expect(parseFloat(ls![1])).toBeLessThanOrEqual(0.08);
  });
});

describe('_tokens.css QUE-47 light/dark structure', () => {
  it(':root is the LIGHT palette (default — no FOUC for the default case)', () => {
    // The :root block must declare the light --bg (white) and a light
    // --text-muted (slate-500, not the dark slate-400).
    const rootMatch = tokens.match(/:root\s*\{([^}]*)\}/);
    expect(rootMatch, ':root block must exist').not.toBeNull();
    const root = rootMatch![1];
    expect(root).toContain('--bg: oklch(1 0 0)');
    expect(root).toContain('--text-muted: #64748b');
    // Semantic on-surface tokens defined in the light default.
    expect(root).toContain('--accent-on-surface');
    expect(root).toContain('--danger-on-surface');
  });

  it('[data-theme="dark"] opts into the dark overrides', () => {
    expect(tokens).toMatch(/\[data-theme="dark"\]\s*\{/);
    const darkMatch = tokens.match(/\[data-theme="dark"\]\s*\{([^}]*)\}/);
    expect(darkMatch, 'data-theme="dark" block must exist').not.toBeNull();
    const dark = darkMatch![1];
    expect(dark).toContain('--bg: oklch(0.208 0.040 265.8)');
    expect(dark).toContain('--text-muted: #94a3b8');
    // The dark block redeclares the on-surface tokens (blue-400 / red-400).
    expect(dark).toContain('--accent-on-surface: oklch(0.714 0.143 254.6)');
    expect(dark).toContain('--danger-on-surface: oklch(0.711 0.166 22.2)');
  });

  it('the former --accent-on-dark / --danger-on-dark names are gone (semantic rename)', () => {
    // Strip CSS comments first — the header prose legitimately mentions the old
    // names while explaining the rename; only the declarations must not use them.
    const declsOnly = tokens.replace(/\/\*[\s\S]*?\*\//g, '');
    expect(declsOnly).not.toContain('--accent-on-dark');
    expect(declsOnly).not.toContain('--danger-on-dark');
  });
});