import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

/**
 * jsdom runs with `css: false` (vitest.config), so stylesheets are NOT applied
 * and computed visibility/opacity/contrast are not testable. CSS-driven ACs are
 * guarded statically here: read styles.css (co-located via import.meta.url —
 * admin-service is `"type": "module"`, so `__dirname` is NOT defined at runtime,
 * ESM-safe via `import.meta.url`), collapse whitespace, and regex-assert the
 * rules. (postcss is not a direct dependency, so a normalized-regex guard is
 * the pragmatic choice.)
 */
const here = dirname(fileURLToPath(import.meta.url));
const css = readFileSync(resolve(here, 'styles.css'), 'utf8').replace(/\s+/g, ' ');
// The vendored token copy (generated by scripts/sync-design-tokens.mjs from the
// canonical shared/design-tokens/tokens.css). Read statically to guard the
// QUE-47 light/dark token structure + the semantic on-surface rename.
const tokens = readFileSync(resolve(here, 'styles/_tokens.css'), 'utf8').replace(/\s+/g, ' ');
// The StateMachineWorkflow / designer component styles (diagram canvas, the
// Diagram↔Source toggle, the JSON source textarea). Read statically to guard
// the dedicated Alur Status Tiket designer view (manager feedback: the inline
// canvas was too small; moved to a full-page route + a Kaleo-style view
// switch). Guarded here because jsdom applies no CSS (css: false).
const wfCss = readFileSync(resolve(here, 'components/state-machine-workflow.css'), 'utf8').replace(/\s+/g, ' ');
// The vendored interaction baseline (generated by scripts/sync-design-tokens.mjs
// from the canonical shared/design-tokens/interactions.css). Read statically to
// guard the element-agnostic `.btn` rule (manager feedback: a `.btn` on a Link
// rendered as underlined inline text, not a button — overlapping positions + a
// visible underline). Guarded here because jsdom applies no CSS (css: false).
const interactionsCss = readFileSync(resolve(here, 'styles/_interactions.css'), 'utf8').replace(/\s+/g, ' ');

/** Same as {@link rule} but against the StateMachineWorkflow component CSS. */
function wfRule(sel: string): string {
  const escaped = sel.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const re = new RegExp(`${escaped}\\s*\\{([^}]*)\\}`);
  const m = wfCss.match(re);
  if (!m) throw new Error(`selector not found in state-machine-workflow.css: ${sel}`);
  return m[1];
}

/** Same as {@link rule} but against the vendored _interactions.css baseline. */
function intRule(sel: string): string {
  const escaped = sel.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const re = new RegExp(`${escaped}\\s*\\{([^}]*)\\}`);
  const m = interactionsCss.match(re);
  if (!m) throw new Error(`selector not found in _interactions.css: ${sel}`);
  return m[1];
}

/** Extracts the declaration block of a selector (greedy to the closing brace). */
function rule(sel: string): string {
  const escaped = sel.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const re = new RegExp(`${escaped}\\s*\\{([^}]*)\\}`);
  const m = css.match(re);
  if (!m) throw new Error(`selector not found: ${sel}`);
  return m[1];
}

/** Extracts the body of a named at-rule block (e.g. `@media (max-width: 900px)`).
 *  The block may contain nested `{}` (CSS rules), so match balanced braces. */
function atRuleBlock(prelude: string): string {
  const escaped = prelude.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const start = css.search(new RegExp(`${escaped}\\s*\\{`));
  if (start === -1) throw new Error(`at-rule not found: ${prelude}`);
  let depth = 0;
  let bodyStart = -1;
  for (let i = start; i < css.length; i++) {
    if (css[i] === '{') {
      if (depth === 0) bodyStart = i + 1;
      depth++;
    } else if (css[i] === '}') {
      depth--;
      if (depth === 0) return css.slice(bodyStart, i);
    }
  }
  throw new Error(`unbalanced braces in at-rule: ${prelude}`);
}

/** Every block sharing a prelude (a breakpoint may be declared more than once,
 *  each next to the section it adjusts). */
function atRuleBlocks(prelude: string): string[] {
  const escaped = prelude.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const re = new RegExp(`${escaped}\\s*\\{`, 'g');
  const blocks: string[] = [];
  for (let m = re.exec(css); m !== null; m = re.exec(css)) {
    let depth = 0;
    let bodyStart = -1;
    for (let i = m.index; i < css.length; i++) {
      if (css[i] === '{') {
        if (depth === 0) bodyStart = i + 1;
        depth++;
      } else if (css[i] === '}') {
        depth--;
        if (depth === 0) {
          blocks.push(css.slice(bodyStart, i));
          break;
        }
      }
    }
  }
  if (blocks.length === 0) throw new Error(`at-rule not found: ${prelude}`);
  return blocks;
}

describe('styles.css AC guards', () => {
  it('wizard hint inside .field resets margin-top so it does not overlap the input above', () => {
    expect(rule('.field .wizard__hint')).toContain('margin-top: 0');
  });

  it('standalone wizard hints keep the intentional negative top margin', () => {
    expect(rule('.wizard__hint')).toContain('margin-top: -0.5rem');
  });

  it('now-serving number uses the accent token (re-themes with the store brand color)', () => {
    expect(rule('.now-serving__number')).toContain('color: var(--accent)');
  });

  it('counter-status active badge uses the success token (semantic "busy")', () => {
    expect(rule('.counter-status__badge--active')).toContain('var(--success)');
  });

  it('counter-status idle badge uses muted surface (semantic "ready, not busy")', () => {
    const idle = rule('.counter-status__badge--idle');
    expect(idle).toContain('var(--surface-2)');
    expect(idle).toContain('var(--text-muted)');
  });

  it('skeleton shimmer is a pure opacity pulse (no background-position gradient)', () => {
    expect(rule('@keyframes skeleton-pulse')).toContain('opacity:');
    // The skeleton keyframes must not animate background-position (the
    // CLAUDE.md recipe is an opacity pulse, not a sliding gradient).
    expect(rule('@keyframes skeleton-pulse')).not.toContain('background-position');
  });

  it('skeleton animation is disabled under prefers-reduced-motion', () => {
    // The reduced-motion block collapses `.skeleton { animation: none }`. The
    // `@media (...)` parenthetical sits between `reduce` and the block brace, so
    // the matcher tolerates a `)` before `{`.
    const reduced = css.match(/prefers-reduced-motion:\s*reduce\)\s*\{[^}]*\.skeleton\s*\{([^}]*)\}/);
    expect(reduced).not.toBeNull();
    expect(reduced![1]).toContain('animation: none');
  });

  it('sr-only clips the label to a 1px AT-only box', () => {
    const sr = rule('.sr-only');
    expect(sr).toContain('clip: rect(0, 0, 0, 0)');
    expect(sr).toContain('position: absolute');
    expect(sr).toContain('width: 1px');
  });

  it('QUE-45 — grouped nav: .nav-group and .nav-group__label rules exist', () => {
    expect(rule('.nav-group')).toContain('flex-direction: column');
    expect(rule('.nav-group__label')).toContain('text-transform: uppercase');
  });

  it('QUE-45 — .nav-link is a flex row with a ≥44px touch target (AC5)', () => {
    expect(rule('.nav-link')).toContain('display: flex');
    expect(rule('.nav-link')).toContain('min-height: 2.75rem');
  });

  it('QUE-45 — nav icon slot sizes the inline svg', () => {
    expect(rule('.nav-icon')).toContain('display: inline-flex');
    expect(rule('.nav-icon svg')).toContain('width: 1.25rem');
  });

  it('the config-section warning is tinted with the warn token, not the danger one', () => {
    // A consequence warning ("this can strand a live ticket"), not an error that
    // already happened — so it must read as caution. jsdom applies no CSS
    // (css: false), so the visual treatment is guarded statically.
    const warning = rule('.admin-panel__warning');
    expect(warning).toContain('var(--warn)');
    expect(warning).not.toContain('var(--danger');
  });

  it('the shared editor warning (.sm-warning) shares the panel warning declaration block', () => {
    // The dropped-standard-status caution must read as caution, not as one of
    // the red `sm-errors` that block saving. It shares the panel warning's block
    // so the two cannot drift; the grouped selector keeps `.admin-panel__warning`
    // last so the `rule()` extractor above still resolves it.
    expect(css).toMatch(/\.sm-warning,\s*\.admin-panel__warning\s*\{/);
    expect(rule('.admin-panel__warning')).toContain('var(--warn)');
  });

  it('the warning carries NO border-left accent stripe (the side-tab idiom must not creep back)', () => {
    // Same uniform-border + color-mix idiom as `.wizard__errors` and `.toast`, so
    // caution, validation errors and toasts read as one family. The grouped
    // selector means this covers `.sm-warning` on the shared StateMachineEditor
    // (which renders under both `.admin-panel` and `.wizard`) too.
    const warning = rule('.admin-panel__warning');
    expect(warning).not.toMatch(/border-left|border-inline-start/);
    expect(warning).toContain('border: 1px solid color-mix(in srgb, var(--warn) 35%,');
  });

  it('the warning bullet list stays inside the tinted box (no default 40px indent)', () => {
    expect(rule('.sm-warning__list')).toContain('padding-left: 1.2rem');
  });

  it('QUE-45 — responsive ≤900px collapses grouped nav: labels hidden, groups inline', () => {
    const media = atRuleBlock('@media (max-width: 900px)');
    // Group labels drop in the horizontal row (the row is too short for them).
    const labelMatch = media.match(/\.nav-group__label\s*\{([^}]*)\}/);
    expect(labelMatch).not.toBeNull();
    expect(labelMatch![1]).toContain('display: none');
    // Groups flow inline.
    const groupMatch = media.match(/\.nav-group\s*\{([^}]*)\}/);
    expect(groupMatch).not.toBeNull();
    expect(groupMatch![1]).toContain('flex-direction: row');
  });

  it('admin-config: the in-content tablist/layout rules are gone (consolidated into the sidebar)', () => {
    // The in-content `ConfigSectionNav` tablist was consolidated into the
    // two-level sidebar; the `.admin-config__layout`/`__nav`/`__nav-item`/
    // `__nav-badge` rules must all be gone so the dead selectors do not drift.
    expect(css).not.toMatch(/\.admin-config__layout\s*\{/);
    expect(css).not.toMatch(/\.admin-config__nav\s*\{/);
    expect(css).not.toMatch(/\.admin-config__nav-item\s*\{/);
    expect(css).not.toMatch(/\.admin-config__nav-item--active\s*\{/);
    expect(css).not.toMatch(/\.admin-config__nav-label\s*\{/);
    expect(css).not.toMatch(/\.admin-config__nav-badge\s*\{/);
    // The content wrapper stays (the per-section content still uses it).
    expect(rule('.admin-config__content')).toContain('min-width: 0');
  });

  it('QUE-45 — two-level nav: .nav-subgroup + .nav-subgroup__label rules exist', () => {
    // The Konfigurasi Sistem group is two-level (Tampilan/Antrean/Sistem). The
    // sub-group label mirrors the big-group label but smaller + more muted.
    expect(rule('.nav-subgroup')).toContain('flex-direction: column');
    expect(rule('.nav-subgroup__label')).toContain('text-transform: uppercase');
    expect(rule('.nav-subgroup__label')).toContain('color: var(--text-muted)');
    expect(rule('.nav-subgroup__items')).toContain('display: flex');
    // Token-only — no hardcoded color (dark mode flips for free).
    expect(rule('.nav-subgroup__label')).not.toMatch(/#[0-9a-fA-F]{3,8}\b/);
  });

  it('QUE-45 — responsive ≤900px flattens the sub-groups into the horizontal row', () => {
    const media = atRuleBlock('@media (max-width: 900px)');
    const labelMatch = media.match(/\.nav-subgroup__label\s*\{([^}]*)\}/);
    expect(labelMatch).not.toBeNull();
    expect(labelMatch![1]).toContain('display: none');
    const itemsMatch = media.match(/\.nav-subgroup__items\s*\{([^}]*)\}/);
    expect(itemsMatch).not.toBeNull();
    expect(itemsMatch![1]).toContain('flex-direction: row');
  });
});

describe('QUE-47 — per-service theme settings section', () => {
  it('renders one row per surface in a flex layout (label + select)', () => {
    expect(rule('.service-themes__grid')).toContain('display: grid');
    expect(rule('.service-themes__row')).toContain('display: flex');
    expect(rule('.service-themes__row')).toContain('align-items: center');
  });

  it('the row label uses the muted text token so it flips with the admin theme', () => {
    expect(rule('.service-themes__label')).toContain('color: var(--text-muted)');
  });
});

describe('toast notifications', () => {
  it('stacks above the routing modal overlay but below the skip link', () => {
    // .modal__overlay is 50 (a toast fired from inside the modal must be
    // readable); .skip-link is 100 (never coverable).
    expect(rule('.toast-viewport')).toContain('z-index: 60');
    expect(rule('.modal__overlay')).toContain('z-index: 50');
    expect(rule('.skip-link')).toContain('z-index: 100');
  });

  it('is click-through as a viewport but clickable per toast', () => {
    expect(rule('.toast-viewport')).toContain('pointer-events: none');
    expect(rule('.toast')).toContain('pointer-events: auto');
    expect(rule('.toast-viewport')).toContain('position: fixed');
  });

  it('gives each live-region wrapper a real box (NOT display: contents)', () => {
    // `display: contents` removes the element from the a11y tree in several
    // engines, which would silently destroy the live region.
    const live = rule('.toast-viewport__live');
    expect(live).toContain('display: flex');
    expect(live).not.toContain('display: contents');
  });

  it('tints each variant with its own semantic token (uniform border + background)', () => {
    // The `.wizard__errors` idiom: a uniform border in the variant hue plus a
    // color-mix tint — NOT a side-tab accent stripe.
    for (const [variant, token] of [
      ['success', '--success'],
      ['error', '--danger'],
      ['info', '--accent'],
    ] as const) {
      const decls = rule(`.toast--${variant}`);
      expect(decls, variant).toContain(`border-color: color-mix(in srgb, var(${token}) 35%,`);
      expect(decls, variant).toContain(`background: color-mix(in srgb, var(${token}) 10%,`);
    }
    expect(rule('.toast--success .toast__icon')).toContain('background: var(--success)');
    expect(rule('.toast--error .toast__icon')).toContain('background: var(--danger)');
    expect(rule('.toast--info .toast__icon')).toContain('background: var(--accent)');
  });

  it('carries NO border-left accent stripe (the side-tab idiom must not creep back)', () => {
    for (const sel of ['.toast', '.toast--success', '.toast--error', '.toast--info']) {
      expect(rule(sel), sel).not.toMatch(/border-left|border-inline-start/);
    }
    expect(rule('.toast')).toContain('border: 1px solid var(--surface-2)');
  });

  it('keeps the dismiss button at the ≥44px touch target', () => {
    const dismiss = rule('.toast__dismiss');
    expect(dismiss).toContain('min-height: 2.75rem');
    expect(dismiss).toContain('min-width: 2.75rem');
  });

  it('animates in, and disables the animation under prefers-reduced-motion', () => {
    expect(rule('.toast')).toContain('animation: toast-in');
    // The `@media` parenthetical `)` sits between the keyword and the block
    // brace, so the matcher must tolerate it (documented gotcha).
    const reduced = css.match(/prefers-reduced-motion:\s*reduce\)\s*\{[^}]*\.toast\s*\{([^}]*)\}/);
    expect(reduced).not.toBeNull();
    expect(reduced![1]).toContain('animation: none');
  });

  it('spans the width on narrow viewports', () => {
    const viewport = atRuleBlocks('@media (max-width: 640px)')
      .map((b) => b.match(/\.toast-viewport\s*\{([^}]*)\}/))
      .find((m) => m !== null);
    expect(viewport).toBeDefined();
    expect(viewport![1]).toContain('width: auto');
    expect(viewport![1]).toContain('left:');
  });

  it('uses zero hardcoded color literals (so [data-theme="dark"] flips for free)', () => {
    for (const sel of [
      '.toast',
      '.toast--success',
      '.toast--error',
      '.toast--info',
      '.toast__icon',
      '.toast__dismiss',
    ]) {
      expect(rule(sel), sel).not.toMatch(/#[0-9a-fA-F]{3,8}\b/);
    }
  });
});

describe('date & time fields', () => {
  it('keeps every new control at the ≥44px touch target', () => {
    for (const sel of [
      '.datefield__toggle',
      '.datefield__clear',
      '.timefield__toggle',
      '.timefield__option',
    ]) {
      expect(rule(sel), sel).toContain('min-height: 2.75rem');
      expect(rule(sel), sel).toContain('min-width: 2.75rem');
    }
  });

  it('positions the popover against the control', () => {
    expect(rule('.datefield__control, .timefield__control')).toContain('position: relative');
    expect(rule('.datefield__popover, .timefield__popover')).toContain('position: absolute');
  });

  it('drives the calendar from our design tokens (the library blue is overridden)', () => {
    // The theming block is grouped across both popovers (DRY) — the range
    // selector is last in the list, so `rule()` (which matches `<sel> {`)
    // resolves it. Assert the single-day selector is also in the group.
    const rdp = rule('.date-range-field__popover .rdp-root');
    expect(rdp).toContain('--rdp-accent-color: var(--accent)');
    expect(rdp).toContain('--rdp-day-height: 2.75rem');
    expect(rdp).toContain('--rdp-day-width: 2.75rem');
    expect(rdp).toContain('color: var(--text)');
    expect(css).toContain('.datefield__popover .rdp-root');
  });

  it('scopes the calendar override one class deeper than the library rule', () => {
    // .datefield__popover .rdp-root / .date-range-field__popover .rdp-root are
    // 0-2-0 vs the library's 0-1-0, so the override wins regardless of
    // stylesheet import order. Both popovers share the theming block (DRY).
    expect(css).toContain('.datefield__popover .rdp-root');
    expect(css).toContain('.date-range-field__popover .rdp-root');
  });

  it('declares the day hover BEFORE the selected fill (equal specificity, order decides)', () => {
    const hover = css.indexOf('.datefield__popover .rdp-day_button:hover');
    const selected = css.indexOf('.datefield__popover .rdp-selected .rdp-day_button');
    expect(hover).toBeGreaterThan(-1);
    expect(selected).toBeGreaterThan(hover);
  });

  it('selects a time cell off the ARIA state itself (no --selected modifier to drift)', () => {
    expect(css).toContain(".timefield__option[aria-pressed='true'] {");
    expect(css).not.toContain('.timefield__option--selected');
  });

  it('uses zero hardcoded color literals', () => {
    for (const sel of [
      '.datefield__toggle',
      '.datefield__clear',
      '.timefield__toggle',
      '.timefield__option',
      '.timefield__column-label',
      '.datefield__popover, .timefield__popover',
      '.date-range-field__popover',
      '.date-range-field__popover .rdp-root',
      '.date-range-field__popover .rdp-selected .rdp-day_button',
    ]) {
      expect(rule(sel), sel).not.toMatch(/#[0-9a-fA-F]{3,8}\b/);
    }
  });
});

describe('_tokens.css QUE-47 light/dark structure', () => {
  it(':root is the LIGHT palette (default — no FOUC for the default case)', () => {
    const rootMatch = tokens.match(/:root\s*\{([^}]*)\}/);
    expect(rootMatch, ':root block must exist').not.toBeNull();
    const root = rootMatch![1];
    expect(root).toContain('--bg: oklch(1 0 0)');
    expect(root).toContain('--text-muted: #64748b');
    expect(root).toContain('--accent-on-surface');
    expect(root).toContain('--danger-on-surface');
  });

  it('[data-theme="dark"] opts into the dark overrides', () => {
    expect(tokens).toMatch(/\[data-theme="dark"\]\s*\{/);
    const darkMatch = tokens.match(/\[data-theme="dark"\]\s*\{([^}]*)\}/);
    expect(darkMatch, 'data-theme="dark" block must exist').not.toBeNull();
    const dark = darkMatch![1];
    expect(dark).toContain('--bg: oklch(0.208 0.040 265.8)');
    expect(dark).toContain('--text-muted: #94a3b8');
    expect(dark).toContain('--accent-on-surface: oklch(0.714 0.143 254.6)');
    expect(dark).toContain('--danger-on-surface: oklch(0.711 0.166 22.2)');
  });

  it('the former --accent-on-dark / --danger-on-dark names are gone (semantic rename)', () => {
    // Strip CSS comments first — header prose may mention the old names while
    // explaining the rename; only the declarations must not use them.
    const declsOnly = tokens.replace(/\/\*[\s\S]*?\*\//g, '');
    expect(declsOnly).not.toContain('--accent-on-dark');
    expect(declsOnly).not.toContain('--danger-on-dark');
  });
});

describe('layout-consistency refactor — shared .page geometry + .page-header', () => {
  it('defines one shared .page rule with the unified geometry (920px / 1rem h-padding)', () => {
    // The unified geometry the four in-shell page roots converged on. Asserting
    // the exact value keeps a future divergent edit from silently re-introducing
    // the 1100px / 1.25rem outlier the refactor removed.
    const page = rule('.page');
    expect(page).toContain('max-width: 920px');
    expect(page).toContain('margin: 0 auto');
    expect(page).toContain('padding: 1.5rem 1rem 2rem');
    expect(page).toContain('display: flex');
    expect(page).toContain('flex-direction: column');
    expect(page).toContain('gap: 1.25rem');
  });

  it('defines the shared .page-header title + subtitle rules', () => {
    expect(rule('.page-header__title')).toContain('font-size: 1.75rem');
    expect(rule('.page-header__subtitle')).toContain('color: var(--text-muted)');
    expect(rule('.page-header__subtitle')).toContain('font-size: 1rem');
  });

  it('defines the .page-header__actions row + the --align-end modifier', () => {
    expect(rule('.page-header__actions')).toContain('display: flex');
    expect(rule('.page-header__actions')).toContain('gap: 0.75rem');
    // The default alignment is center (no modifier); the modifier flips it.
    expect(rule('.page-header__actions--align-end')).toContain('align-items: flex-end');
  });

  it('the per-page __title / __subtitle rules are gone (replaced by .page-header)', () => {
    expect(css).not.toMatch(/\.status-dashboard__title\s*\{/);
    expect(css).not.toMatch(/\.status-dashboard__subtitle\s*\{/);
    expect(css).not.toMatch(/\.analytics__title\s*\{/);
    expect(css).not.toMatch(/\.analytics__subtitle\s*\{/);
    expect(css).not.toMatch(/\.admin-panel__title\s*\{/);
    expect(css).not.toMatch(/\.admin-panel__subtitle\s*\{/);
    expect(css).not.toMatch(/\.users__title\s*\{/);
    expect(css).not.toMatch(/\.users__subtitle\s*\{/);
  });

  it('the per-page __header + __controls rules are gone (replaced by .page-header)', () => {
    expect(css).not.toMatch(/\.status-dashboard__header\s*\{/);
    expect(css).not.toMatch(/\.status-dashboard__controls\s*\{/);
    expect(css).not.toMatch(/\.analytics__header\s*\{/);
    expect(css).not.toMatch(/\.analytics__controls\s*\{/);
    expect(css).not.toMatch(/\.admin-panel__header\s*\{/);
    expect(css).not.toMatch(/\.users__header\s*\{/);
  });

  it('the per-page root geometry blocks are gone — .page is the single geometry source', () => {
    // .status-dashboard, .analytics, .users, .admin-panel no longer carry ANY
    // geometry rule — .page supplies max-width/margin/padding/flex. The selector
    // may still appear in comment prose, so assert the rule block (selector +
    // brace) does not declare geometry.
    expect(css).not.toMatch(/\.status-dashboard\s*\{[^}]*max-width/);
    expect(css).not.toMatch(/\.analytics\s*\{[^}]*max-width/);
    expect(css).not.toMatch(/\.users\s*\{[^}]*max-width/);
    // `.admin-panel` has NO bare base rule at all — every state composes `.page`.
    // A bare `.admin-panel {` would re-introduce a duplicated geometry source
    // (DRY). The two-class `.admin-panel.admin-panel--loading` override below is
    // the only `.admin-panel`-rooted rule, and `\s*\{` does not match the
    // `.admin-panel--loading` suffix, so this guard sees a true bare base if one
    // is ever re-added.
    expect(css).not.toMatch(/\.admin-panel\s*\{/);
  });

  it('.admin-panel--loading overrides padding via a two-class selector that beats .page', () => {
    // The loading state composes `.page` (for the 920px max-width + centering)
    // then overrides only the padding. A two-class selector (0,2,0) beats
    // `.page`'s one-class `padding` regardless of source order — so `.page`
    // stays the single geometry source and the loading state keeps its 3rem
    // centered text. Guards the arch-review cleaner approach.
    const loading = rule('.admin-panel.admin-panel--loading');
    expect(loading).toContain('padding: 3rem');
    expect(loading).toContain('text-align: center');
  });

  it('.status-dashboard no longer carries the divergent 1100px / 1.25rem outlier', () => {
    // The refactor specifically converged .status-dashboard from 1100px / 1.25rem
    // onto the shared 920px / 1rem geometry. Guard the exact old values stay gone
    // so a future edit cannot silently re-introduce the divergence.
    expect(css).not.toMatch(/\.status-dashboard[^{]*\{[^}]*1100px/);
    expect(css).not.toMatch(/\.status-dashboard[^{]*\{[^}]*1\.25rem\s+1\.25rem/);
  });

  it('reserves the scrollbar gutter on the root scroller so /admin/config does not resize across sections', () => {
    // The sectioned /admin/config nav mounts ONE section at a time, so document
    // height — and thus the vertical scrollbar's presence — changes per section.
    // Without a reserved gutter the centered `.page` shifts/resizes when the bar
    // toggles (the "membesar dan mengecil" the manager reported). `scrollbar-gutter:
    // stable` on the root scroller (`html`) keeps the inline size constant. Guard
    // it on `html` (the viewport scroller), not `body`.
    const html = rule('html');
    expect(html).toContain('scrollbar-gutter: stable');
  });
});

describe('relative-range presets + range-trend bar/line toggle', () => {
  it('.relative-range is a flex-wrap cluster', () => {
    const r = rule('.relative-range');
    expect(r).toContain('display: flex');
    expect(r).toContain('flex-wrap: wrap');
  });

  it('.relative-range__btn keeps the ≥44px touch target + token-only colors', () => {
    const btn = rule('.relative-range__btn');
    expect(btn).toContain('min-height: 2.75rem');
    expect(btn).not.toMatch(/#[0-9a-fA-F]{3,8}\b/);
  });

  it('selects the active preset off the ARIA state itself (no --active modifier to drift)', () => {
    expect(css).toContain(".relative-range__btn[aria-pressed='true']");
    expect(css).not.toContain('.relative-range__btn--active');
    // The active selector must NOT be wrapped in `:where(...)` — `:where()`
    // zeroes specificity (0,0,0) so the `.relative-range__btn` base (0,1,0)
    // would win and the pressed preset would be visually identical to inactive.
    // A plain attribute selector (0,1,1) beats the base (mirrors
    // `.timefield__option[aria-pressed='true']`).
    expect(css).not.toMatch(/:where\(\.relative-range__btn\[/);
    const active = rule(".relative-range__btn[aria-pressed='true']");
    expect(active).toContain('background: var(--accent)');
    expect(active).toContain('color: var(--accent-contrast)');
  });

  it('.analytics__custom-range is gone (the manual range is a single DateRangeField rendered directly, no wrapper)', () => {
    // The manual Dari/Sampai panel used to be a flex-wrap row of two DateFields
    // under a `.analytics__custom-range` wrapper. The unified `DateRangeField`
    // (now reveal-on-custom per manager feedback) renders directly below the
    // PageHeader with NO wrapper class, so the old `.analytics__custom-range`
    // rule must be gone entirely (no orphan selector to drift).
    expect(css).not.toMatch(/\.analytics__custom-range\s*\{/);
  });

  it('.date-range-field__trigger is a ≥44px textbox-styled button capped to a comfortable width (manager feedback: rentang tanggal terlalu wide)', () => {
    // The trigger is a single button styled as a textbox; the calendar glyph
    // lives INSIDE it (no separate toggle). `width:100%` lets it fill narrow
    // containers, while `max-width` caps it on the wide analytics page so the
    // rentang tanggal is no longer terlalu wide. The popover anchors to the
    // full-width `.date-range-field` root, so the cap does NOT shrink the
    // two-month calendar popover.
    const t = rule('.date-range-field__trigger');
    expect(t).toContain('display: inline-flex');
    expect(t).toContain('width: 100%');
    expect(t).toContain('max-width: 22rem');
    expect(t).toContain('min-height: 2.75rem');
    expect(t).toContain('text-align: left');
    expect(t).not.toMatch(/#[0-9a-fA-F]{3,8}\b/);
  });

  it('.range-trend__svg has a FIXED height (no height:auto → dashboard layout stays stable across ranges + modes)', () => {
    // Manager feedback: "Tren Pengunjung heightnya terlalu dinamis". The prior
    // `height:auto` + a viewBox width that grew with the day count made the
    // rendered height swing from tall (7 days) to short (90 days), so the
    // dashboard jumped on every range/mode change. The viewBox width is now
    // fixed (RangeTrendChart) and the CSS height is fixed here — guard the
    // fixed height and the absence of `height:auto` so the dynamism cannot
    // silently creep back (jsdom runs css:false, so this is a static guard).
    // Strip CSS comments first — the explanatory comment mentions `height:auto`
    // by name and would otherwise self-trip the `not.toMatch`.
    const svg = rule('.range-trend__svg').replace(/\/\*[\s\S]*?\*\//g, '');
    expect(svg).toContain('height: 15rem');
    expect(svg).not.toMatch(/height:\s*auto/);
  });

  it('.date-range-field__popover is an absolute 2-month-wide panel under the trigger', () => {
    const p = rule('.date-range-field__popover');
    expect(p).toContain('position: absolute');
    expect(p).toContain('z-index: 20');
    expect(p).toContain('max-width: 100%');
    expect(p).not.toMatch(/#[0-9a-fA-F]{3,8}\b/);
  });

  it('selects the open trigger off the ARIA state itself (no --active modifier to drift)', () => {
    expect(css).toContain(".date-range-field__trigger[aria-expanded='true']");
    expect(css).not.toContain('.date-range-field__trigger--active');
  });

  it('.range-trend__head lays the h2 + mode toggle in a space-between flex row', () => {
    const head = rule('.range-trend__head');
    expect(head).toContain('display: flex');
    expect(head).toContain('justify-content: space-between');
    expect(head).toContain('align-items: center');
    expect(head).toContain('flex-wrap: wrap');
  });

  it('.range-trend__mode-btn keeps the ≥44px touch target + selects active off the ARIA state', () => {
    const btn = rule('.range-trend__mode-btn');
    expect(btn).toContain('min-height: 2.75rem');
    expect(css).toContain(".range-trend__mode-btn[aria-pressed='true']");
    expect(css).not.toContain('.range-trend__mode-btn--active');
    // Same `:where()` guard as the relative-range active selector — see above.
    expect(css).not.toMatch(/:where\(\.range-trend__mode-btn\[/);
  });

  it('the line mark + point use the accent token (single-hue series, text never wears the data color)', () => {
    expect(rule('.range-trend__line')).toContain('stroke: var(--accent)');
    expect(rule('.range-trend__line')).toContain('fill: none');
    expect(rule('.range-trend__point')).toContain('fill: var(--accent)');
  });

  it('uses zero hardcoded color literals in the new selectors', () => {
    for (const sel of [
      '.relative-range',
      '.relative-range__btn',
      '.range-trend__head',
      '.range-trend__mode',
      '.range-trend__mode-btn',
      '.range-trend__line',
      '.range-trend__point',
    ]) {
      expect(rule(sel), sel).not.toMatch(/#[0-9a-fA-F]{3,8}\b/);
    }
  });
});

describe('Alur Status Tiket designer — warning relocation + dedicated full-page diagram', () => {
  it('the section warning sits before the action (not hoisted above the title — the `--top` modifier is gone)', () => {
    // Manager feedback moved this twice: the warning was first hoisted to the
    // VERY TOP of the card (above the <h2>) via `--top`; that overcorrected — a
    // caution detached from the action it cautions. It now sits at the decision
    // point, immediately before the "Lihat Diagram" link, and the title is the
    // first child again (matches every other config section). Lock the reversal:
    // the `--top` modifier rule is gone, and the base `.admin-panel__warning`
    // rule still carries its margin.
    expect(css).not.toMatch(/\.admin-panel__warning--top\s*\{/);
    const base = rule('.admin-panel__warning');
    expect(base).toContain('margin:');
  });

  it('the designer page root drops the 920px cap so the canvas fills <main> width', () => {
    // Manager feedback: the inline diagram was too small. The designer route is
    // NOT a `.page` (it carries its own geometry) — it must NOT inherit the
    // 920px max-width or the canvas is cramped again. Guard both the presence of
    // the root rule and the absence of the cap.
    const designer = rule('.alur-status-designer');
    expect(designer).toContain('display: flex');
    expect(designer).toContain('flex-direction: column');
    expect(designer).not.toMatch(/max-width:\s*920px/);
  });

  it('the designer canvas is tall (descendant selector beats the base .sm-canvas height)', () => {
    // The base `.sm-canvas` (60vh / min 360px) is the inline config-card size the
    // manager found too small. `.alur-status-designer .sm-canvas` (specificity
    // 0-2-0) overrides it without changing the StateMachineWorkflow API. Guard
    // the tall height + the larger min-height.
    const canvas = wfRule('.alur-status-designer .sm-canvas');
    expect(canvas).toContain('height: calc(100vh - 16rem)');
    expect(canvas).toContain('min-height: 30rem');
  });

  it('selects the active view off the ARIA state itself (no --active modifier to drift)', () => {
    // The active view button reads as the selected affordance via the brand
    // accent (token-driven so light/dark + brandColor re-themes apply), NOT a
    // hardcoded color literal. Following the codebase convention
    // (`timefield__option`, `relative-range__btn`, `range-trend__mode-btn`),
    // the ARIA state IS the selector — so the visual and announced state cannot
    // drift. No `--active` modifier class duplicates the ARIA state.
    expect(wfCss).toContain(".sm-view-toggle__btn[aria-pressed='true']");
    expect(wfCss).not.toContain('.sm-view-toggle__btn--active');
    const active = wfRule(".sm-view-toggle__btn[aria-pressed='true']");
    expect(active).toContain('background: var(--accent)');
    expect(active).toContain('color: var(--accent-contrast)');
  });

  it('the JSON source textarea is a monospace input over the token surface (no hardcoded color)', () => {
    // The Source view is an editable JSON textarea (Kaleo-style view switch).
    // Monospace keeps the JSON column-aligned; token border/surface so it reads
    // as an input under both themes. No hardcoded color literal — dark mode
    // flips it for free.
    const source = wfRule('.sm-source');
    expect(source).toContain('font-family: ui-monospace');
    expect(source).toContain('background: var(--surface)');
    expect(source).not.toMatch(/#[0-9a-fA-F]{3,8}\b/);
  });

  it('the source error region uses the danger-on-surface text token (a validation error, not a caution)', () => {
    // An invalid JSON parse / validation failure blocks the save — it reads as
    // an error, so it uses `--danger-on-surface` (text-on-surface semantic),
    // distinct from the `--warn` caution the section warning uses.
    const err = wfRule('.sm-source-error');
    expect(err).toContain('color: var(--danger-on-surface)');
  });

  it('renders a connector legend (from → to) so the source shows which point connects to which', () => {
    // Manager feedback: the raw JSON source did not explain which point
    // connects to which (ruwet). The Source view now renders a read-only
    // connector legend between the hint and the textarea. The legend container
    // is a token-surface panel (scrollable so a large graph never pushes the
    // textarea off-screen) — no hardcoded color, dark mode flips it for free.
    expect(wfCss).toContain('.sm-source-connectors');
    const connectors = wfRule('.sm-source-connectors');
    expect(connectors).toContain('display: flex');
    expect(connectors).toContain('overflow-y: auto');
    expect(connectors).toContain('background: var(--surface-2)');
    expect(connectors).not.toMatch(/#[0-9a-fA-F]{3,8}\b/);
    // One chip per transition.
    const chip = wfRule('.sm-source-connector');
    expect(chip).toContain('display: inline-flex');
    expect(chip).toContain('font-family: ui-monospace');
  });

  it('colors the connector arrow with the brand accent (the direction indicator, no hardcoded hex)', () => {
    // The arrow glyph is the connector's "this way" cue — brand accent so it
    // reads as the directed edge, mirroring the React Flow arrowhead in the
    // Diagram view. Token-driven so light/dark + brandColor re-theme apply.
    const arrow = wfRule('.sm-source-connector__arrow');
    expect(arrow).toContain('color: var(--accent)');
    expect(arrow).not.toMatch(/#[0-9a-fA-F]{3,8}\b/);
    // The from/to status names use the text token (not a hardcoded literal).
    expect(wfRule('.sm-source-connector__from')).toContain('color: var(--text)');
    expect(wfRule('.sm-source-connector__to')).toContain('color: var(--text)');
    // The action-label annotation uses the muted token, visually parted from
    // the from→to pair by a hairline border (no hardcoded color).
    const label = wfRule('.sm-source-connector__label');
    expect(label).toContain('color: var(--text-muted)');
    expect(label).not.toMatch(/#[0-9a-fA-F]{3,8}\b/);
  });
});

describe('shared .btn baseline is element-agnostic (manager feedback: Link-as-btn overlapped + underlined)', () => {
  // The "Lihat Diagram" / "Kembali" affordances on /admin/config + the designer
  // are `<Link>` (anchors) carrying `className="btn btn--…"`. The shared `.btn`
  // baseline MUST render the SAME button box on an anchor as on a `<button>`:
  //   - `display: inline-block` — an anchor is `display: inline` by default, so
  //     its vertical padding (0.9rem) overflows the line box and overlaps the
  //     content above/below ("tumpang tindih"). inline-block makes it a proper
  //     box on its own line. A native <button> is already inline-block, so this
  //     changes nothing for button-based `.btn`.
  //   - `text-decoration: none` — an anchor carries the default underline; a
  //     <button> does not. Without this, the Link-as-btn showed an underline
  //     ("button ada garis bawahnya") and did not read as the shared button.
  //   - `text-align: center` — a native <button> centers its label; an
  //     inline-block anchor is left-aligned by default. Match the button look.
  // These three lift anchor-based `.btn` to parity with button-based `.btn`; the
  // detector cannot catch the regression (jsdom runs css:false), so guard here.
  it('.btn sets display:inline-block, text-decoration:none, and text-align:center', () => {
    const btn = intRule('.btn');
    expect(btn).toContain('display: inline-block');
    expect(btn).toContain('text-decoration: none');
    expect(btn).toContain('text-align: center');
  });
});
