import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

/**
 * jsdom runs with `css: false` (vitest.config), so stylesheets are NOT applied
 * and computed visibility/opacity/contrast are not testable. CSS-driven ACs are
 * guarded statically here: read styles.css (co-located via import.meta.url —
 * admin-service is `"type": "module"`, so `__dirname` is NOT defined at runtime,
 * ESM-safe via `import.meta.url`), collapse whitespace, and regex-assert the
 * rules. (postcss is not a direct dependency, so a normalized-regex guard is
 * the pragmatic choice.)
 */
const here = dirname(fileURLToPath(import.meta.url));
const css = readFileSync(resolve(here, 'styles.css'), 'utf8').replace(/\s+/g, ' ');
// The vendored token copy (generated by scripts/sync-design-tokens.mjs from the
// canonical shared/design-tokens/tokens.css). Read statically to guard the
// QUE-47 light/dark token structure + the semantic on-surface rename.
const tokens = readFileSync(resolve(here, 'styles/_tokens.css'), 'utf8').replace(/\s+/g, ' ');

/** Extracts the declaration block of a selector (greedy to the closing brace). */
function rule(sel: string): string {
  const escaped = sel.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const re = new RegExp(`${escaped}\\s*\\{([^}]*)\\}`);
  const m = css.match(re);
  if (!m) throw new Error(`selector not found: ${sel}`);
  return m[1];
}

/** Extracts the body of a named at-rule block (e.g. `@media (max-width: 900px)`).
 *  The block may contain nested `{}` (CSS rules), so match balanced braces. */
function atRuleBlock(prelude: string): string {
  const escaped = prelude.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const start = css.search(new RegExp(`${escaped}\\s*\\{`));
  if (start === -1) throw new Error(`at-rule not found: ${prelude}`);
  let depth = 0;
  let bodyStart = -1;
  for (let i = start; i < css.length; i++) {
    if (css[i] === '{') {
      if (depth === 0) bodyStart = i + 1;
      depth++;
    } else if (css[i] === '}') {
      depth--;
      if (depth === 0) return css.slice(bodyStart, i);
    }
  }
  throw new Error(`unbalanced braces in at-rule: ${prelude}`);
}

/** Every block sharing a prelude (a breakpoint may be declared more than once,
 *  each next to the section it adjusts). */
function atRuleBlocks(prelude: string): string[] {
  const escaped = prelude.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const re = new RegExp(`${escaped}\\s*\\{`, 'g');
  const blocks: string[] = [];
  for (let m = re.exec(css); m !== null; m = re.exec(css)) {
    let depth = 0;
    let bodyStart = -1;
    for (let i = m.index; i < css.length; i++) {
      if (css[i] === '{') {
        if (depth === 0) bodyStart = i + 1;
        depth++;
      } else if (css[i] === '}') {
        depth--;
        if (depth === 0) {
          blocks.push(css.slice(bodyStart, i));
          break;
        }
      }
    }
  }
  if (blocks.length === 0) throw new Error(`at-rule not found: ${prelude}`);
  return blocks;
}

describe('styles.css AC guards', () => {
  it('wizard hint inside .field resets margin-top so it does not overlap the input above', () => {
    expect(rule('.field .wizard__hint')).toContain('margin-top: 0');
  });

  it('standalone wizard hints keep the intentional negative top margin', () => {
    expect(rule('.wizard__hint')).toContain('margin-top: -0.5rem');
  });

  it('now-serving number uses the accent token (re-themes with the store brand color)', () => {
    expect(rule('.now-serving__number')).toContain('color: var(--accent)');
  });

  it('counter-status active badge uses the success token (semantic "busy")', () => {
    expect(rule('.counter-status__badge--active')).toContain('var(--success)');
  });

  it('counter-status idle badge uses muted surface (semantic "ready, not busy")', () => {
    const idle = rule('.counter-status__badge--idle');
    expect(idle).toContain('var(--surface-2)');
    expect(idle).toContain('var(--text-muted)');
  });

  it('skeleton shimmer is a pure opacity pulse (no background-position gradient)', () => {
    expect(rule('@keyframes skeleton-pulse')).toContain('opacity:');
    // The skeleton keyframes must not animate background-position (the
    // CLAUDE.md recipe is an opacity pulse, not a sliding gradient).
    expect(rule('@keyframes skeleton-pulse')).not.toContain('background-position');
  });

  it('skeleton animation is disabled under prefers-reduced-motion', () => {
    // The reduced-motion block collapses `.skeleton { animation: none }`. The
    // `@media (...)` parenthetical sits between `reduce` and the block brace, so
    // the matcher tolerates a `)` before `{`.
    const reduced = css.match(/prefers-reduced-motion:\s*reduce\)\s*\{[^}]*\.skeleton\s*\{([^}]*)\}/);
    expect(reduced).not.toBeNull();
    expect(reduced![1]).toContain('animation: none');
  });

  it('sr-only clips the label to a 1px AT-only box', () => {
    const sr = rule('.sr-only');
    expect(sr).toContain('clip: rect(0, 0, 0, 0)');
    expect(sr).toContain('position: absolute');
    expect(sr).toContain('width: 1px');
  });

  it('QUE-45 — grouped nav: .nav-group and .nav-group__label rules exist', () => {
    expect(rule('.nav-group')).toContain('flex-direction: column');
    expect(rule('.nav-group__label')).toContain('text-transform: uppercase');
  });

  it('QUE-45 — .nav-link is a flex row with a ≥44px touch target (AC5)', () => {
    expect(rule('.nav-link')).toContain('display: flex');
    expect(rule('.nav-link')).toContain('min-height: 2.75rem');
  });

  it('QUE-45 — nav icon slot sizes the inline svg', () => {
    expect(rule('.nav-icon')).toContain('display: inline-flex');
    expect(rule('.nav-icon svg')).toContain('width: 1.25rem');
  });

  it('the config-section warning is tinted with the warn token, not the danger one', () => {
    // A consequence warning ("this can strand a live ticket"), not an error that
    // already happened — so it must read as caution. jsdom applies no CSS
    // (css: false), so the visual treatment is guarded statically.
    const warning = rule('.admin-panel__warning');
    expect(warning).toContain('var(--warn)');
    expect(warning).not.toContain('var(--danger');
  });

  it('the shared editor warning (.sm-warning) shares the panel warning declaration block', () => {
    // The dropped-standard-status caution must read as caution, not as one of
    // the red `sm-errors` that block saving. It shares the panel warning's block
    // so the two cannot drift; the grouped selector keeps `.admin-panel__warning`
    // last so the `rule()` extractor above still resolves it.
    expect(css).toMatch(/\.sm-warning,\s*\.admin-panel__warning\s*\{/);
    expect(rule('.admin-panel__warning')).toContain('var(--warn)');
  });

  it('the warning carries NO border-left accent stripe (the side-tab idiom must not creep back)', () => {
    // Same uniform-border + color-mix idiom as `.wizard__errors` and `.toast`, so
    // caution, validation errors and toasts read as one family. The grouped
    // selector means this covers `.sm-warning` on the shared StateMachineEditor
    // (which renders under both `.admin-panel` and `.wizard`) too.
    const warning = rule('.admin-panel__warning');
    expect(warning).not.toMatch(/border-left|border-inline-start/);
    expect(warning).toContain('border: 1px solid color-mix(in srgb, var(--warn) 35%,');
  });

  it('the warning bullet list stays inside the tinted box (no default 40px indent)', () => {
    expect(rule('.sm-warning__list')).toContain('padding-left: 1.2rem');
  });

  it('QUE-45 — responsive ≤900px collapses grouped nav: labels hidden, groups inline', () => {
    const media = atRuleBlock('@media (max-width: 900px)');
    // Group labels drop in the horizontal row (the row is too short for them).
    const labelMatch = media.match(/\.nav-group__label\s*\{([^}]*)\}/);
    expect(labelMatch).not.toBeNull();
    expect(labelMatch![1]).toContain('display: none');
    // Groups flow inline.
    const groupMatch = media.match(/\.nav-group\s*\{([^}]*)\}/);
    expect(groupMatch).not.toBeNull();
    expect(groupMatch![1]).toContain('flex-direction: row');
  });

  it('admin-config: two-column grid layout (sticky left nav + right content)', () => {
    expect(rule('.admin-config__layout')).toContain('display: grid');
    expect(rule('.admin-config__layout')).toMatch(/grid-template-columns:\s*minmax\(11rem,\s*16rem\)\s+1fr/);
    expect(rule('.admin-config__nav')).toContain('position: sticky');
    expect(rule('.admin-config__nav')).toContain('flex-direction: column');
  });

  it('admin-config: nav item is a ≥44px touch target with a left active indicator', () => {
    expect(rule('.admin-config__nav-item')).toContain('min-height: 2.75rem');
    expect(rule('.admin-config__nav-item')).toContain('border-left: 3px solid transparent');
    const active = rule('.admin-config__nav-item--active');
    expect(active).toContain('var(--accent)');
    expect(active).toContain('var(--accent-on-surface)');
  });

  it('admin-config: error badge uses the danger token (never color alone — .sr-only carries AT text)', () => {
    expect(rule('.admin-config__nav-badge')).toContain('var(--danger)');
    // The badge is a small dot, not a text-colored element.
    expect(rule('.admin-config__nav-badge')).not.toContain('color:');
  });

  it('admin-config: responsive ≤900px stacks the layout into a wrapping nav row', () => {
    const media = atRuleBlock('@media (max-width: 900px)');
    const layoutMatch = media.match(/\.admin-config__layout\s*\{([^}]*)\}/);
    expect(layoutMatch).not.toBeNull();
    expect(layoutMatch![1]).toContain('grid-template-columns: 1fr');
    const navMatch = media.match(/\.admin-config__nav\s*\{([^}]*)\}/);
    expect(navMatch).not.toBeNull();
    expect(navMatch![1]).toContain('flex-direction: row');
    expect(navMatch![1]).toContain('position: static');
  });
});

describe('QUE-47 — per-service theme settings section', () => {
  it('renders one row per surface in a flex layout (label + select)', () => {
    expect(rule('.service-themes__grid')).toContain('display: grid');
    expect(rule('.service-themes__row')).toContain('display: flex');
    expect(rule('.service-themes__row')).toContain('align-items: center');
  });

  it('the row label uses the muted text token so it flips with the admin theme', () => {
    expect(rule('.service-themes__label')).toContain('color: var(--text-muted)');
  });
});

describe('toast notifications', () => {
  it('stacks above the routing modal overlay but below the skip link', () => {
    // .modal__overlay is 50 (a toast fired from inside the modal must be
    // readable); .skip-link is 100 (never coverable).
    expect(rule('.toast-viewport')).toContain('z-index: 60');
    expect(rule('.modal__overlay')).toContain('z-index: 50');
    expect(rule('.skip-link')).toContain('z-index: 100');
  });

  it('is click-through as a viewport but clickable per toast', () => {
    expect(rule('.toast-viewport')).toContain('pointer-events: none');
    expect(rule('.toast')).toContain('pointer-events: auto');
    expect(rule('.toast-viewport')).toContain('position: fixed');
  });

  it('gives each live-region wrapper a real box (NOT display: contents)', () => {
    // `display: contents` removes the element from the a11y tree in several
    // engines, which would silently destroy the live region.
    const live = rule('.toast-viewport__live');
    expect(live).toContain('display: flex');
    expect(live).not.toContain('display: contents');
  });

  it('tints each variant with its own semantic token (uniform border + background)', () => {
    // The `.wizard__errors` idiom: a uniform border in the variant hue plus a
    // color-mix tint — NOT a side-tab accent stripe.
    for (const [variant, token] of [
      ['success', '--success'],
      ['error', '--danger'],
      ['info', '--accent'],
    ] as const) {
      const decls = rule(`.toast--${variant}`);
      expect(decls, variant).toContain(`border-color: color-mix(in srgb, var(${token}) 35%,`);
      expect(decls, variant).toContain(`background: color-mix(in srgb, var(${token}) 10%,`);
    }
    expect(rule('.toast--success .toast__icon')).toContain('background: var(--success)');
    expect(rule('.toast--error .toast__icon')).toContain('background: var(--danger)');
    expect(rule('.toast--info .toast__icon')).toContain('background: var(--accent)');
  });

  it('carries NO border-left accent stripe (the side-tab idiom must not creep back)', () => {
    for (const sel of ['.toast', '.toast--success', '.toast--error', '.toast--info']) {
      expect(rule(sel), sel).not.toMatch(/border-left|border-inline-start/);
    }
    expect(rule('.toast')).toContain('border: 1px solid var(--surface-2)');
  });

  it('keeps the dismiss button at the ≥44px touch target', () => {
    const dismiss = rule('.toast__dismiss');
    expect(dismiss).toContain('min-height: 2.75rem');
    expect(dismiss).toContain('min-width: 2.75rem');
  });

  it('animates in, and disables the animation under prefers-reduced-motion', () => {
    expect(rule('.toast')).toContain('animation: toast-in');
    // The `@media` parenthetical `)` sits between the keyword and the block
    // brace, so the matcher must tolerate it (documented gotcha).
    const reduced = css.match(/prefers-reduced-motion:\s*reduce\)\s*\{[^}]*\.toast\s*\{([^}]*)\}/);
    expect(reduced).not.toBeNull();
    expect(reduced![1]).toContain('animation: none');
  });

  it('spans the width on narrow viewports', () => {
    const viewport = atRuleBlocks('@media (max-width: 640px)')
      .map((b) => b.match(/\.toast-viewport\s*\{([^}]*)\}/))
      .find((m) => m !== null);
    expect(viewport).toBeDefined();
    expect(viewport![1]).toContain('width: auto');
    expect(viewport![1]).toContain('left:');
  });

  it('uses zero hardcoded color literals (so [data-theme="dark"] flips for free)', () => {
    for (const sel of [
      '.toast',
      '.toast--success',
      '.toast--error',
      '.toast--info',
      '.toast__icon',
      '.toast__dismiss',
    ]) {
      expect(rule(sel), sel).not.toMatch(/#[0-9a-fA-F]{3,8}\b/);
    }
  });
});

describe('date & time fields', () => {
  it('keeps every new control at the ≥44px touch target', () => {
    for (const sel of [
      '.datefield__toggle',
      '.datefield__clear',
      '.timefield__toggle',
      '.timefield__option',
    ]) {
      expect(rule(sel), sel).toContain('min-height: 2.75rem');
      expect(rule(sel), sel).toContain('min-width: 2.75rem');
    }
  });

  it('positions the popover against the control', () => {
    expect(rule('.datefield__control, .timefield__control')).toContain('position: relative');
    expect(rule('.datefield__popover, .timefield__popover')).toContain('position: absolute');
  });

  it('drives the calendar from our design tokens (the library blue is overridden)', () => {
    const rdp = rule('.datefield__popover .rdp-root');
    expect(rdp).toContain('--rdp-accent-color: var(--accent)');
    expect(rdp).toContain('--rdp-day-height: 2.75rem');
    expect(rdp).toContain('--rdp-day-width: 2.75rem');
    expect(rdp).toContain('color: var(--text)');
  });

  it('scopes the calendar override one class deeper than the library rule', () => {
    // .datefield__popover .rdp-root is 0-2-0 vs the library's 0-1-0, so the
    // override wins regardless of stylesheet import order.
    expect(css).toContain('.datefield__popover .rdp-root {');
  });

  it('declares the day hover BEFORE the selected fill (equal specificity, order decides)', () => {
    const hover = css.indexOf('.datefield__popover .rdp-day_button:hover');
    const selected = css.indexOf('.datefield__popover .rdp-selected .rdp-day_button');
    expect(hover).toBeGreaterThan(-1);
    expect(selected).toBeGreaterThan(hover);
  });

  it('selects a time cell off the ARIA state itself (no --selected modifier to drift)', () => {
    expect(css).toContain(".timefield__option[aria-pressed='true'] {");
    expect(css).not.toContain('.timefield__option--selected');
  });

  it('uses zero hardcoded color literals', () => {
    for (const sel of [
      '.datefield__toggle',
      '.datefield__clear',
      '.timefield__toggle',
      '.timefield__option',
      '.timefield__column-label',
      '.datefield__popover, .timefield__popover',
      '.datefield__popover .rdp-root',
      '.datefield__popover .rdp-selected .rdp-day_button',
    ]) {
      expect(rule(sel), sel).not.toMatch(/#[0-9a-fA-F]{3,8}\b/);
    }
  });
});

describe('_tokens.css QUE-47 light/dark structure', () => {
  it(':root is the LIGHT palette (default — no FOUC for the default case)', () => {
    const rootMatch = tokens.match(/:root\s*\{([^}]*)\}/);
    expect(rootMatch, ':root block must exist').not.toBeNull();
    const root = rootMatch![1];
    expect(root).toContain('--bg: oklch(1 0 0)');
    expect(root).toContain('--text-muted: #64748b');
    expect(root).toContain('--accent-on-surface');
    expect(root).toContain('--danger-on-surface');
  });

  it('[data-theme="dark"] opts into the dark overrides', () => {
    expect(tokens).toMatch(/\[data-theme="dark"\]\s*\{/);
    const darkMatch = tokens.match(/\[data-theme="dark"\]\s*\{([^}]*)\}/);
    expect(darkMatch, 'data-theme="dark" block must exist').not.toBeNull();
    const dark = darkMatch![1];
    expect(dark).toContain('--bg: oklch(0.208 0.040 265.8)');
    expect(dark).toContain('--text-muted: #94a3b8');
    expect(dark).toContain('--accent-on-surface: oklch(0.714 0.143 254.6)');
    expect(dark).toContain('--danger-on-surface: oklch(0.711 0.166 22.2)');
  });

  it('the former --accent-on-dark / --danger-on-dark names are gone (semantic rename)', () => {
    // Strip CSS comments first — header prose may mention the old names while
    // explaining the rename; only the declarations must not use them.
    const declsOnly = tokens.replace(/\/\*[\s\S]*?\*\//g, '');
    expect(declsOnly).not.toContain('--accent-on-dark');
    expect(declsOnly).not.toContain('--danger-on-dark');
  });
});